name: CI/CD Pipeline

on:
  workflow_dispatch:   # ✅ Manual trigger with dropdowns
    inputs:
      environment:
        description: "Select the environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

      version:
        description: "Select the version (tag/branch/commit)"
        required: true
        default: "latest"
        type: string

      run_tests:
        description: "Run tests?"
        required: true
        default: true
        type: boolean

  push:                # ✅ Auto-trigger on code push
    branches: [ main ]

  pull_request:        # ✅ Auto-trigger on PR open/update
    types: [opened, synchronize, reopened]

  release:             # ✅ Auto-trigger when a release is published
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
