# .github/workflows/deploy.yml
name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs: 
      environment: 
        description: "Select the environment"
        required: false
        type: choice
        options: 
          - "dev"
          - "prod"

      version:
        description: "Select the version (tag/branch/commit)"
        required: true
        default: "latest"
        type: string

      run_tests:
        description: "Run tests?"
        required: true
        default: true
        type: boolean

      ecr_deploy:
        description: "Push image to ECR?"
        default: false
        type: boolean

  push:
  release:
  pull_request:
    types:
      - opened
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: npm ci
    - run: npm run build --if-present
